name: Sanitizers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 5"

jobs:
  asan:
    name: ASan (nightly, linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: test (asan)
        env:
          RUSTFLAGS: "-Zsanitizer=address"
          ASAN_OPTIONS: "detect_leaks=0"
        run: cargo test -Zbuild-std

  tsan:
    name: TSan (nightly, linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: test (tsan)
        env:
          RUSTFLAGS: "-Zsanitizer=thread"
        run: cargo test -Zbuild-std
